CREATE DATABASE IF NOT EXISTS uniformes;
USE uniformes;

CREATE TABLE IF NOT EXISTS estoque (
  id INT(11) NOT NULL AUTO_INCREMENT,
  data DATE DEFAULT NULL,
  codigo VARCHAR(50) DEFAULT NULL,
  produto VARCHAR(50) DEFAULT NULL,
  tamanho VARCHAR(10) DEFAULT NULL,
  cor VARCHAR(20) DEFAULT NULL,
  quantidade INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;